In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
score_data = pd.read_csv('scores.csv', index_col=[0,1])

In [3]:
data_2group = score_data.drop('is_churn',axis=1)

In [4]:
data_2group

,,like_per_month,newfriend_per_month,post_per_month,adview_per_month,dislike_per_month,unfriend_per_month,message_per_month,reply_per_month,account_tenure,adview_per_post,reply_per_message,like_per_post,post_per_message,unfriend_per_newfriend,dislike_pcnt,unfriend_per_newfriend_scaled,newfriend_pcnt_chng,days_since_newfriend,unfriend_28day_avg_84day_obs,unfriend_28day_avg_84day_obs_scaled
account_id,observation_date,,,,,,,,,,,,,,,,,,,,
27,2020-03-01,-0.252128,0.176105,-0.250193,0.449681,-1.074832,1.271113,-1.913326,-1.681545,-0.600623,0.794364,-1.524524,-0.151952,2.123692,0.702322,-0.789858,0.165914,3.220524,-0.073812,0.310313,0.505493
51,2020-03-01,-0.306824,0.176105,-1.186311,0.010731,-0.593460,1.271113,0.397880,0.851668,-0.600623,1.777259,1.034653,1.111640,-0.860022,0.702322,-0.468472,0.804718,-0.436188,-0.683207,1.444420,1.792298
95,2020-03-01,0.475167,0.176105,0.999259,-0.076426,0.758881,-0.551847,-0.503272,-0.217639,-0.600623,-0.987500,0.506809,-0.607365,1.140677,-0.403228,-0.085544,-0.534873,0.232470,-0.683207,-0.823795,-0.781313
123,2020-03-01,-0.252128,0.347369,-0.308981,-1.136047,0.960141,-0.551847,-0.563570,-1.160091,-0.600623,-0.927775,-1.088607,-0.082986,-0.074285,-0.403228,1.162712,-0.534873,1.257860,-0.326734,-0.823795,-0.781313
189,2020-03-01,-1.768424,-1.044471,-0.685463,-0.123708,-1.074832,-0.551847,-2.435484,-1.681545,-0.600623,0.588915,-1.524524,-1.227813,-0.963738,-0.403228,0.817071,-0.534873,-0.167825,1.144979,-0.823795,-0.781313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13132,2020-05-10,-0.536530,-1.814568,0.036512,-1.558615,-0.803737,-0.551847,0.074712,-0.217639,-1.722229,-1.243688,-0.519187,-0.746014,-0.331772,-0.403228,-0.453864,-0.534873,-0.167825,-1.292602,-0.823795,-0.781313
13141,2020-05-10,-1.768424,-1.044471,-0.899606,-0.562658,-1.456919,-0.551847,-0.447446,-0.333606,-1.722229,0.255892,0.105805,-1.107822,-0.531085,-0.403228,0.093953,-0.534873,-0.167825,1.296065,-0.823795,-0.781313
13155,2020-05-10,-1.988622,-1.814568,-1.967073,-1.894027,-1.456919,-0.551847,0.074712,0.492879,-1.722229,-0.151696,0.922067,-0.151952,-0.922276,-0.403228,0.495685,-0.534873,-0.167825,-1.292602,-0.823795,-0.781313
13171,2020-05-10,-0.707328,0.347369,0.685924,-0.123708,-1.456919,-0.551847,0.047315,-0.217639,-1.722229,-0.851258,-0.484275,-1.262435,0.165409,-0.403228,-0.809944,-0.534873,-0.167825,0.418187,-0.823795,-0.781313
13248,2020-05-10,1.829413,2.553752,2.234475,2.909376,1.477078,1.271113,2.165020,1.276363,-1.722229,0.820646,-0.994444,-0.354298,-0.416495,-0.283150,-0.672083,-0.374764,-0.167825,-1.292602,0.310313,2.049659

In [5]:
load_mat_df = pd.read_csv('load_matrix.csv', index_col=[0])

In [6]:
load_mat_ndarray = load_mat_df.to_numpy()

In [7]:
ndarray_2group = data_2group[load_mat_df.index.values].to_numpy()

In [8]:
ndarray_2group

array([[-0.25212808,  0.17610487, -0.25019323, ..., -0.07381164,
         0.31031282,  0.5054926 ],
       [-0.30682414,  0.17610487, -1.1863105 , ..., -0.68320699,
         1.44442037,  1.79229809],
       [ 0.47516726,  0.17610487,  0.9992589 , ..., -0.68320699,
        -0.82379465, -0.78131288],
       ...,
       [-1.98862184, -1.81456811, -1.96707328, ..., -1.29260234,
        -0.82379465, -0.78131288],
       [-0.70732828,  0.34736871,  0.68592405, ...,  0.41818669,
        -0.82379465, -0.78131288],
       [ 1.82941306,  2.55375208,  2.23447529, ..., -1.29260234,
         0.31031282,  2.04965924]], shape=(25806, 20))

In [9]:
grouped_ndarray = np.matmul(
    ndarray_2group,
    load_mat_ndarray)

In [10]:
churn_data_grouped = pd.DataFrame(
    grouped_ndarray, 
    columns=load_mat_df.columns.values, 
    index=score_data.index
)

In [11]:
churn_data_grouped['is_churn'] = score_data['is_churn']
churn_data_grouped

,,metric_group_0,metric_group_1,metric_group_2,dislike_per_month,account_tenure,reply_per_message,dislike_pcnt,newfriend_pcnt_chng,days_since_newfriend,is_churn
account_id,observation_date,,,,,,,,,,
27,2020-03-01,0.583781,0.835844,-2.541958,-1.074832,-0.600623,-1.524524,-0.789858,3.220524,-0.073812,False
51,2020-03-01,0.145983,1.701262,0.883564,-0.593460,-0.600623,1.034653,-0.468472,-0.436188,-0.683207,False
95,2020-03-01,0.226257,-0.875414,-0.509761,0.758881,-0.600623,0.506809,-0.085544,0.232470,-0.683207,False
123,2020-03-01,-0.491911,-0.875414,-1.218812,0.960141,-0.600623,-1.088607,1.162712,1.257860,-0.326734,False
189,2020-03-01,-1.055549,-0.875414,-2.911179,-1.074832,-0.600623,-1.524524,0.817071,-0.167825,1.144979,True
...,...,...,...,...,...,...,...,...,...,...,...
13132,2020-05-10,-1.251514,-0.875414,-0.101065,-0.803737,-1.722229,-0.519187,-0.453864,-0.167825,-1.292602,False
13141,2020-05-10,-1.143124,-0.875414,-0.552287,-1.456919,-1.722229,0.105805,0.093953,-0.167825,1.296065,False
13155,2020-05-10,-1.796094,-0.875414,0.401347,-1.456919,-1.722229,0.922067,0.495685,-0.167825,-1.292602,False
13171,2020-05-10,-0.352751,-0.875414,-0.120437,-1.456919,-1.722229,-0.484275,-0.809944,-0.167825,0.418187,False
13248,2020-05-10,1.934820,0.840939,2.433426,1.477078,-1.722229,-0.994444,-0.672083,-0.167825,-1.292602,False

In [12]:
churn_data_grouped.to_csv('groupscore.csv')

In [13]:
data_2group.columns

Index(['like_per_month', 'newfriend_per_month', 'post_per_month',
       'adview_per_month', 'dislike_per_month', 'unfriend_per_month',
       'message_per_month', 'reply_per_month', 'account_tenure',
       'adview_per_post', 'reply_per_message', 'like_per_post',
       'post_per_message', 'unfriend_per_newfriend', 'dislike_pcnt',
       'unfriend_per_newfriend_scaled', 'newfriend_pcnt_chng',
       'days_since_newfriend', 'unfriend_28day_avg_84day_obs',
       'unfriend_28day_avg_84day_obs_scaled'],
      dtype='str')

In [14]:
load_mat_df.index

Index(['like_per_month', 'newfriend_per_month', 'post_per_month',
       'adview_per_month', 'dislike_per_month', 'unfriend_per_month',
       'message_per_month', 'reply_per_month', 'account_tenure',
       'adview_per_post', 'reply_per_message', 'like_per_post',
       'post_per_message', 'unfriend_per_newfriend', 'dislike_pcnt',
       'unfriend_per_newfriend_scaled', 'newfriend_pcnt_chng',
       'days_since_newfriend', 'unfriend_28day_avg_84day_obs',
       'unfriend_28day_avg_84day_obs_scaled'],
      dtype='str')

In [15]:
churn_data_grouped

,,metric_group_0,metric_group_1,metric_group_2,dislike_per_month,account_tenure,reply_per_message,dislike_pcnt,newfriend_pcnt_chng,days_since_newfriend,is_churn
account_id,observation_date,,,,,,,,,,
27,2020-03-01,0.583781,0.835844,-2.541958,-1.074832,-0.600623,-1.524524,-0.789858,3.220524,-0.073812,False
51,2020-03-01,0.145983,1.701262,0.883564,-0.593460,-0.600623,1.034653,-0.468472,-0.436188,-0.683207,False
95,2020-03-01,0.226257,-0.875414,-0.509761,0.758881,-0.600623,0.506809,-0.085544,0.232470,-0.683207,False
123,2020-03-01,-0.491911,-0.875414,-1.218812,0.960141,-0.600623,-1.088607,1.162712,1.257860,-0.326734,False
189,2020-03-01,-1.055549,-0.875414,-2.911179,-1.074832,-0.600623,-1.524524,0.817071,-0.167825,1.144979,True
...,...,...,...,...,...,...,...,...,...,...,...
13132,2020-05-10,-1.251514,-0.875414,-0.101065,-0.803737,-1.722229,-0.519187,-0.453864,-0.167825,-1.292602,False
13141,2020-05-10,-1.143124,-0.875414,-0.552287,-1.456919,-1.722229,0.105805,0.093953,-0.167825,1.296065,False
13155,2020-05-10,-1.796094,-0.875414,0.401347,-1.456919,-1.722229,0.922067,0.495685,-0.167825,-1.292602,False
13171,2020-05-10,-0.352751,-0.875414,-0.120437,-1.456919,-1.722229,-0.484275,-0.809944,-0.167825,0.418187,False
13248,2020-05-10,1.934820,0.840939,2.433426,1.477078,-1.722229,-0.994444,-0.672083,-0.167825,-1.292602,False